name: Test

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - closed
      - opened
      - reopened
      - synchronize
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  tagged:
    if: startsWith(github.ref, 'refs/tags/')
    name: Tagged
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: ${{ toJSON(github) }} > ./event.json
      - uses: actions/upload-artifact@v4
        with:
          name: tagged-event
          path: ./event.json

  pull-request:
    if: github.event_name == 'pull_request'
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: bash
        env:
          GITHUB: ${{ toJSON(github) }}
        run: $GITHUB > ./event.json
      - uses: actions/upload-artifact@v4
        with:
          name: pull-request-event
          path: ./event.json
      - name: Step 2
        if: github.event.action != 'closed'
        shell: bash
        run: echo "Not closed".
