name: Test

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - closed
      - opened
      - reopened
      - synchronize
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    if: startsWith(github.ref, 'refs/tags/')
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: echo ${{ github.event }}

  pull-request:
    if: github.event_name == 'pull_request'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: bash
        run: echo ${{ github.event }}
      - name: Step 2
        if: github.event.action != 'closed'
        shell: bash
        run: echo "Not closed".
